networks:
  cont4bl3:
    external: true

services:
  cont4bl3_nginx:
    image: nginx:latest
    container_name: cont4bl3_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - cont4bl3
